kind: wasmer.io/App.v0
name: AumigosWebTeste
owner: larissanunescosta1
package: .
env:
  APP_ENV: staging
  APP_DEBUG: "true"
  APP_KEY: "base64:aBE4cU46PycQxwZ7v9zq3IkLxUJYXUK//8I4ef8Lu/8="
  DB_CONNECTION: mysql
  SESSION_DRIVER: database
  CACHE_STORE: database
  QUEUE_CONNECTION: sync
  LOG_CHANNEL: stderr
capabilities:
  database:
    engine: mysql

locality:
  regions:
    - fr-roub1
app_id: da_RrWI0t5UDmXZ
